[package]
name = "cargo-count"
version = "0.1.2"
authors = ["Kevin K <kbknapp@gmail.com>"]

[dependencies]
clap = "~1.4"
glob = "~0.2"
tabwriter = "~0.1"
regex = "~0.1.41"
ansi_term = {version = "~0.6.3", optional = true}
clippy = {version = "~0.0", optional = true}

[features]
default = ["color"]
color = ["ansi_term"]
debug = []
lints = ["clippy", "unstable"]
unstable = []
